"""Authenticated localhost review inbox for one-at-a-time approval."""

from __future__ import annotations

import hashlib
import hmac
import html
import urllib.parse
from datetime import date
from http import HTTPStatus
from http.cookies import SimpleCookie
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

from markdown_it import MarkdownIt

from jarvis.community_briefing.service import CommunityBriefingService

from .discord import (
    DISCORD_PURPOSE_MAX_LENGTH,
    discord_purpose_for_publication,
)
from .models import PublicationStatus
from .notes import MEETING_NOTE_MAX_LENGTH
from .notify import review_token
from .service import PublicationService

_COOKIE_NAME = "jarvis_meeting_review"
_MAX_REVIEW_FORM_BYTES = 1_000_000


def create_review_server(
    service: PublicationService,
    briefing_service: CommunityBriefingService | None = None,
) -> ThreadingHTTPServer:
    """Create a loopback-only server; callers control its lifecycle."""

    token = review_token(service.state_root)
    handler = _handler_class(service, token, briefing_service)
    return ThreadingHTTPServer((service.config.review_host, service.config.review_port), handler)


def serve_review(
    service: PublicationService,
    briefing_service: CommunityBriefingService | None = None,
) -> None:
    """Run the local review inbox until interrupted."""

    server = create_review_server(service, briefing_service)
    try:
        server.serve_forever()
    finally:
        server.server_close()


def _handler_class(
    service: PublicationService,
    token: str,
    briefing_service: CommunityBriefingService | None,
) -> type[BaseHTTPRequestHandler]:
    class ReviewHandler(BaseHTTPRequestHandler):
        server_version = "JarvisMeetingReview/1"

        def log_message(self, format: str, *args: object) -> None:
            return

        def do_GET(self) -> None:  # noqa: N802
            parsed = urllib.parse.urlsplit(self.path)
            query = urllib.parse.parse_qs(parsed.query)
            supplied = query.get("token", [""])[0]
            authenticated = self._cookie_token_valid() or hmac.compare_digest(supplied, token)
            if not authenticated:
                self._write(
                    HTTPStatus.UNAUTHORIZED,
                    _message_page("Unauthorized", "Use the local review link generated by Jarvis."),
                )
                return
            headers = {}
            if supplied:
                headers["Set-Cookie"] = f"{_COOKIE_NAME}={token}; HttpOnly; SameSite=Strict; Path=/"
            if parsed.path == "/":
                self._write(
                    HTTPStatus.OK,
                    _inbox_page(service, token, briefing_service),
                    headers=headers,
                )
                return
            if parsed.path.startswith("/briefing/") and briefing_service is not None:
                briefing_id = parsed.path.removeprefix("/briefing/").strip("/")
                self._write(
                    HTTPStatus.OK,
                    _briefing_page(briefing_service, briefing_id, token),
                    headers=headers,
                )
                return
            if parsed.path.startswith("/item/"):
                item_id = parsed.path.removeprefix("/item/").strip("/")
                self._write(HTTPStatus.OK, _item_page(service, item_id, token), headers=headers)
                return
            self._write(HTTPStatus.NOT_FOUND, _message_page("Not found", "Unknown review page."))

        def do_POST(self) -> None:  # noqa: N802
            if not self._cookie_token_valid():
                self._write(
                    HTTPStatus.UNAUTHORIZED,
                    _message_page("Unauthorized", "Reload the authenticated local review link."),
                )
                return
            try:
                length = min(
                    int(self.headers.get("Content-Length", "0")),
                    _MAX_REVIEW_FORM_BYTES,
                )
            except ValueError:
                length = 0
            form = urllib.parse.parse_qs(self.rfile.read(length).decode("utf-8", errors="replace"))
            supplied = form.get("csrf", [""])[0]
            if not hmac.compare_digest(supplied, _csrf(token)):
                self._write(
                    HTTPStatus.FORBIDDEN,
                    _message_page("Forbidden", "The review form expired. Reload it and try again."),
                )
                return
            path = urllib.parse.urlsplit(self.path).path
            try:
                if path.startswith("/briefing/save/") and briefing_service is not None:
                    briefing_service.save_draft(
                        path.removeprefix("/briefing/save/").strip("/"),
                        markdown=form.get("briefing_markdown", [""])[0],
                        discord_summary=form.get("discord_summary", [""])[0],
                    )
                    destination = path.removeprefix("/briefing/save/").strip("/")
                    self.send_response(HTTPStatus.SEE_OTHER)
                    self.send_header("Location", f"/briefing/{destination}")
                    self.end_headers()
                    return
                if path.startswith("/update-note/"):
                    destination = path.removeprefix("/update-note/").strip("/")
                    service.update_note(
                        destination,
                        markdown=form.get("meeting_markdown", [""])[0],
                    )
                    self.send_response(HTTPStatus.SEE_OTHER)
                    self.send_header("Location", f"/item/{destination}")
                    self.end_headers()
                    return
                if path.startswith("/briefing/approve/") and briefing_service is not None:
                    briefing_service.approve(
                        path.removeprefix("/briefing/approve/").strip("/"),
                        markdown=form.get("briefing_markdown", [""])[0],
                        discord_summary=form.get("discord_summary", [""])[0],
                    )
                elif path.startswith("/briefing/reject/") and briefing_service is not None:
                    briefing_service.reject(path.removeprefix("/briefing/reject/").strip("/"))
                elif path.startswith("/approve/"):
                    reviewed_summary = form.get("discord_summary")
                    meeting_markdown = form.get("meeting_markdown")
                    service.approve(
                        path.removeprefix("/approve/").strip("/"),
                        meeting_markdown=(meeting_markdown[0] if meeting_markdown else None),
                        discord_summary=reviewed_summary[0] if reviewed_summary else None,
                    )
                elif path.startswith("/reject/"):
                    service.reject(path.removeprefix("/reject/").strip("/"))
                else:
                    self._write(
                        HTTPStatus.NOT_FOUND, _message_page("Not found", "Unknown review action.")
                    )
                    return
            except (KeyError, OSError, UnicodeError, ValueError) as exc:
                self._write(
                    HTTPStatus.CONFLICT, _message_page("Review changed", html.escape(str(exc)))
                )
                return
            self.send_response(HTTPStatus.SEE_OTHER)
            self.send_header("Location", "/")
            self.end_headers()

        def _cookie_token_valid(self) -> bool:
            cookie = SimpleCookie()
            cookie.load(self.headers.get("Cookie", ""))
            morsel = cookie.get(_COOKIE_NAME)
            return bool(morsel and hmac.compare_digest(morsel.value, token))

        def _write(
            self,
            status: HTTPStatus,
            body: str,
            *,
            headers: dict[str, str] | None = None,
        ) -> None:
            encoded = body.encode("utf-8")
            self.send_response(status)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(encoded)))
            self.send_header("Cache-Control", "no-store")
            self.send_header(
                "Content-Security-Policy",
                "default-src 'none'; style-src 'unsafe-inline'; "
                "form-action 'self'; base-uri 'none'; frame-ancestors 'none'",
            )
            self.send_header("X-Content-Type-Options", "nosniff")
            self.send_header("Referrer-Policy", "no-referrer")
            for key, value in (headers or {}).items():
                self.send_header(key, value)
            self.end_headers()
            self.wfile.write(encoded)

    return ReviewHandler


def _inbox_page(
    service: PublicationService,
    token: str,
    briefing_service: CommunityBriefingService | None = None,
) -> str:
    pending = service.store.list_items(PublicationStatus.PENDING_REVIEW)
    blocked = service.store.list_items(PublicationStatus.BLOCKED)
    counts = service.store.counts()
    briefing_pending = (
        briefing_service.store.list_items(PublicationStatus.PENDING_REVIEW)
        if briefing_service is not None
        else []
    )
    if pending:
        item = pending[0]
        body = f"""
        <header class="page-intro">
          <p class="eyebrow">Flow Research · Publication queue</p>
          <div class="intro-row">
            <div>
              <h1>Publication review</h1>
              <p class="lede">Review weekly briefings and meetings before anything is published.</p>
            </div>
            <span class="count-badge">{len(pending)} waiting</span>
          </div>
        </header>
        <section class="card queue-card">
          <p class="section-label">Next meeting</p>
          <h2>{html.escape(item.title)}</h2>
          <div class="meta-row">
            <span class="meta-pill">{_format_date(item.meeting_date)}</span>
            <span class="meta-pill">Flow</span>
            <span class="status-pill status-{item.status.value}">{_status_label(item.status)}</span>
          </div>
          <a class="button primary-button" href="/item/{item.item_id}">
            Review meeting <span aria-hidden="true">→</span>
          </a>
        </section>
        """
    else:
        lede = (
            "A weekly briefing is waiting below. No meetings need review."
            if briefing_pending
            else "Everything has been reviewed. New publications will appear here automatically."
        )
        body = f"""
        <header class="page-intro">
          <p class="eyebrow">Flow Research · Publication queue</p>
          <h1>Publication review</h1>
          <p class="lede">{lede}</p>
        </header>
        <section class="card empty-card"><div class="empty-icon">✓</div><h2>Queue clear</h2>
        <p>No meetings are waiting for review.</p></section>
        """
    if briefing_service is not None:
        briefing_blocked = briefing_service.store.list_items(PublicationStatus.BLOCKED)
        if briefing_pending:
            briefing = briefing_pending[0]
            briefing_range = f"{briefing.week_start.isoformat()} to {briefing.week_end.isoformat()}"
            briefing_status = _status_label(briefing.status)
            briefing_card = f"""
            <section class="card queue-card">
              <p class="section-label">Weekly community briefing</p>
              <h2>Week of {_format_date(briefing.week_start)}</h2>
              <div class="meta-row">
                <span class="meta-pill">{briefing_range}</span>
                <span class="status-pill status-{briefing.status.value}">{briefing_status}</span>
              </div>
              <a class="button primary-button" href="/briefing/{briefing.briefing_id}">
                Review briefing <span aria-hidden="true">→</span>
              </a>
            </section>
            """
            body = body.replace("</header>", "</header>" + briefing_card, 1)
        if briefing_blocked:
            body += (
                '<section class="card attention-card"><p class="section-label">'
                "Weekly briefing needs attention</p><ul>"
            )
            body += "".join(
                f"<li>Week of {_format_date(item.week_start)} — "
                f"{html.escape(item.error_message or 'Configuration error')}</li>"
                for item in briefing_blocked
            )
            body += "</ul></section>"
        briefing_counts = briefing_service.store.counts()
        body += (
            '<details class="card queue-status"><summary>Weekly briefing status</summary>'
            '<div class="status-grid">'
            + "".join(
                "<div><span>"
                f"{html.escape(key.replace('_', ' ').title())}"
                f"</span><strong>{value}</strong></div>"
                for key, value in briefing_counts.items()
            )
            + "</div></details>"
        )
    if blocked:
        body += (
            '<section class="card attention-card"><p class="section-label">Needs attention</p><ul>'
        )
        body += "".join(
            f"<li>{html.escape(item.title)} — "
            f"{html.escape(item.error_message or 'Configuration error')}</li>"
            for item in blocked
        )
        body += "</ul></section>"
    body += (
        '<details class="card queue-status"><summary>Queue status</summary>'
        '<div class="status-grid">'
        + "".join(
            "<div><span>"
            f"{html.escape(key.replace('_', ' ').title())}"
            f"</span><strong>{value}</strong></div>"
            for key, value in counts.items()
        )
        + "</div></details>"
    )
    return _page("Publication review", body)


def _briefing_page(
    service: CommunityBriefingService,
    briefing_id: str,
    token: str,
) -> str:
    """Render both editable artifacts and the current public preview."""

    item = service.store.get(briefing_id)
    if item is None:
        return _message_page("Not found", "That weekly briefing is not in the local queue.")
    try:
        markdown, discord_summary = service.read_artifacts(item)
    except (OSError, UnicodeError) as exc:
        return _message_page("Cannot read briefing", html.escape(str(exc)))
    csrf = _csrf(token)
    editable = item.status == PublicationStatus.PENDING_REVIEW
    item_range = f"{item.week_start.isoformat()} to {item.week_end.isoformat()}"
    item_status = _status_label(item.status)
    if editable:
        actions = f"""
        <section class="card action-card">
          <p class="section-label">Decision</p>
          <h2>Ready to publish?</h2>
          <p>Approval covers the exact briefing and Discord copy shown here.</p>
          <form id="briefing-approve" method="post"
            action="/briefing/approve/{item.briefing_id}">
            <input type="hidden" name="csrf" value="{csrf}">
            <button class="approve" type="submit">Approve &amp; publish</button>
            <button class="save-draft" type="submit"
              formaction="/briefing/save/{item.briefing_id}">Save draft</button>
          </form>
          <form method="post" action="/briefing/reject/{item.briefing_id}">
            <input type="hidden" name="csrf" value="{csrf}">
            <button class="reject" type="submit">Reject</button>
          </form>
          <p class="privacy-note">Nothing is sent until the publication worker sees approval.</p>
        </section>
        """
        editors = f"""
        <label class="discord-editor-label" for="briefing-markdown">Google Doc briefing</label>
        <textarea class="briefing-editor" id="briefing-markdown"
          name="briefing_markdown" form="briefing-approve" maxlength="50000" required
          spellcheck="true">{html.escape(markdown)}</textarea>
        <label class="discord-editor-label" for="briefing-discord">Discord copy</label>
        <textarea class="discord-summary" id="briefing-discord"
          name="discord_summary" form="briefing-approve" maxlength="600" required
          spellcheck="true">{html.escape(discord_summary)}</textarea>
        <p class="discord-editor-help">Use no more than three concise sentences.</p>
        """
    else:
        actions = f"""
        <section class="card action-card"><p class="section-label">Decision</p>
        <h2>{_status_label(item.status)}</h2>
        <p>This briefing is no longer awaiting review.</p></section>
        """
        editors = ""
    body = f"""
      <a class="back-link" href="/"><span aria-hidden="true">←</span> Review inbox</a>
      <header class="meeting-header">
        <p class="eyebrow">Flow Research · Weekly community briefing</p>
        <h1>Week of {_format_date(item.week_start)}</h1>
        <div class="meta-row">
          <span class="meta-pill">{item_range}</span>
          <span class="status-pill status-{item.status.value}">{item_status}</span>
        </div>
      </header>
      <div class="review-grid">
        <main class="card note-card">
          <div class="section-heading"><div><p class="section-label">Current preview</p>
          <h2>Weekly briefing</h2></div><span class="local-badge">Private draft</span></div>
          <article class="markdown-body meeting-note">{_render_markdown(markdown)}</article>
          {editors}
        </main>
        <aside class="review-sidebar">
          <section class="card preview-card">
            <p class="section-label">Discord preview</p>
            <div class="discord-shell"><div class="discord-avatar" aria-hidden="true">F</div>
            <div class="discord-message"><div class="discord-author">
            Flow Research <span>BOT</span></div>
            <div>{html.escape(discord_summary)}</div>
            <div class="discord-doc-link">↗ Read the weekly briefing</div></div></div>
          </section>
          {actions}
        </aside>
      </div>
    """
    return _page("Weekly community briefing review", body)


def _item_page(service: PublicationService, item_id: str, token: str) -> str:
    item = service.store.get(item_id)
    if item is None:
        return _message_page("Not found", "That meeting is not in the local queue.")
    try:
        note = service.load_live_note(item_id)
    except (OSError, UnicodeError, ValueError) as exc:
        return _message_page("Cannot read note", html.escape(str(exc)))
    if note.source_hash != item.source_hash:
        service.store.upsert_note(note)
        return _message_page(
            "Meeting changed",
            "The note changed on disk. Return to the inbox to review the latest version.",
        )
    csrf = _csrf(token)
    summary = discord_purpose_for_publication(
        note,
        summary_override=item.discord_summary_override,
    )
    summary_editor = (
        f"""<label class="discord-editor-label" for="discord-summary">
          Discord purpose sentence
        </label>
        <textarea class="discord-summary" id="discord-summary"
          name="discord_summary" form="approve-form"
          maxlength="{DISCORD_PURPOSE_MAX_LENGTH}" required
          aria-describedby="discord-summary-help"
          spellcheck="true">{html.escape(summary)}</textarea>
        <p class="discord-editor-help" id="discord-summary-help">
          Keep this to one short sentence. It does not alter the meeting note.
        </p>"""
        if item.status == PublicationStatus.PENDING_REVIEW
        else f'<div class="discord-summary-static">{html.escape(summary)}</div>'
    )
    actions: str
    if item.status == PublicationStatus.PENDING_REVIEW:
        actions = f"""
        <section class="card action-card">
          <p class="section-label">Decision</p>
          <h2>Ready to publish?</h2>
          <p>Approval applies only to this exact version of the note.</p>
          <div class="actions">
          <form id="approve-form" method="post" action="/approve/{item.item_id}">
            <input type="hidden" name="csrf" value="{csrf}">
            <button class="approve" type="submit">Approve &amp; publish</button>
            <button class="save-note" type="submit"
              formaction="/update-note/{item.item_id}">Update meeting note</button>
          </form>
          <form method="post" action="/reject/{item.item_id}">
            <input type="hidden" name="csrf" value="{csrf}">
            <button class="reject" type="submit">Reject</button>
          </form>
          </div>
          <p class="privacy-note">
            Updating writes the canonical local Markdown and keeps this meeting unapproved.
          </p>
        </section>
        """
    else:
        actions = f"""
        <section class="card action-card">
          <p class="section-label">Decision</p>
          <h2>{_status_label(item.status)}</h2>
          <p>This meeting is no longer awaiting review.</p>
        </section>
        """
    metadata_markdown, note_markdown = _split_note_markdown(note.markdown)
    metadata = (
        f"""<details class="metadata-card">
          <summary>Meeting metadata</summary>
          <div class="markdown-body metadata-body">{_render_markdown(metadata_markdown)}</div>
        </details>"""
        if metadata_markdown
        else ""
    )
    note_editor = (
        f"""<label class="meeting-editor-label" for="meeting-markdown">
          Edit meeting note Markdown
        </label>
        <textarea class="meeting-note-editor" id="meeting-markdown"
          name="meeting_markdown" form="approve-form"
          maxlength="{MEETING_NOTE_MAX_LENGTH}" required
          aria-describedby="meeting-markdown-help"
          spellcheck="true">{html.escape(note.markdown)}</textarea>
        <p class="meeting-editor-help" id="meeting-markdown-help">
          Update meeting note writes this canonical file locally but does not approve or publish it.
        </p>"""
        if item.status == PublicationStatus.PENDING_REVIEW
        else ""
    )
    body = f"""
      <a class="back-link" href="/"><span aria-hidden="true">←</span> Review inbox</a>
      <header class="meeting-header">
        <p class="eyebrow">Flow Research · Meeting review</p>
        <h1>{html.escape(note.title)}</h1>
        <div class="meta-row">
          <span class="meta-pill">{_format_date(note.meeting_date)}</span>
          <span class="meta-pill">Flow</span>
          <span class="status-pill status-{item.status.value}">{_status_label(item.status)}</span>
        </div>
      </header>
      <div class="review-grid">
        <main class="card note-card">
          <div class="section-heading">
            <div><p class="section-label">Canonical source</p><h2>Meeting note</h2></div>
            <span class="local-badge">Local Markdown</span>
          </div>
          {metadata}
          <article class="markdown-body meeting-note">{_render_markdown(note_markdown)}</article>
          {note_editor}
        </main>
        <aside class="review-sidebar">
          <section class="card preview-card">
            <div class="section-heading preview-heading">
              <div><p class="section-label">Destination preview</p><h2>Discord</h2></div>
              <span class="summary-badge">Summary only</span>
            </div>
            <div class="discord-shell">
              <div class="discord-avatar" aria-hidden="true">F</div>
              <div class="discord-message">
                <div class="discord-author">Flow Research <span>BOT</span></div>
                <div class="discord-title">{html.escape(note.title)}</div>
                <div class="discord-date">{note.meeting_date.isoformat()} · Flow</div>
                {summary_editor}
                <div class="discord-doc-link">↗ Read the full meeting notes</div>
              </div>
            </div>
          </section>
          {actions}
        </aside>
      </div>
    """
    return _page(note.title, body)


def _csrf(token: str) -> str:
    return hashlib.sha256(f"meeting-review:{token}".encode()).hexdigest()


def _render_markdown(markdown: str) -> str:
    """Render untrusted meeting Markdown without allowing embedded HTML."""

    renderer = MarkdownIt(
        "commonmark",
        {"html": False, "linkify": False, "typographer": False},
    )
    rendered = str(renderer.render(markdown))
    return rendered.replace("<a href=", '<a target="_blank" rel="noopener noreferrer" href=')


def _split_note_markdown(markdown: str) -> tuple[str, str]:
    """Separate noisy metadata and the duplicate title from the readable note."""

    lines = markdown.splitlines()
    while lines and not lines[0].strip():
        lines.pop(0)
    if lines and lines[0].startswith("# "):
        lines.pop(0)
    while lines and not lines[0].strip():
        lines.pop(0)

    metadata: list[str] = []
    note: list[str] = []
    in_metadata = False
    for line in lines:
        if line.strip().lower() == "## metadata":
            in_metadata = True
            continue
        if in_metadata and line.startswith("## "):
            in_metadata = False
        if in_metadata:
            metadata.append(line)
        else:
            note.append(line)
    return "\n".join(metadata).strip(), "\n".join(note).strip()


def _format_date(value: date) -> str:
    return f"{value:%B} {value.day}, {value.year}"


def _status_label(status: PublicationStatus) -> str:
    return status.value.replace("_", " ").title()


def _message_page(title: str, message: str) -> str:
    return _page(
        title,
        f"""<section class="card message-card"><p class="eyebrow">Publication review</p>
        <h1>{html.escape(title)}</h1><p>{message}</p>
        <a class="button primary-button" href="/">Return to inbox</a></section>""",
    )


def _page(title: str, body: str) -> str:
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>{html.escape(title)}</title><style>
:root {{ color-scheme:light; --canvas:#f3f6f4; --surface:#fff; --ink:#15201a;
--muted:#647068; --line:#dce4df; --accent:#167449; --accent-dark:#105b39;
--danger:#a33b3b; --discord:#313338; }}
* {{ box-sizing:border-box; }}
body {{ background:var(--canvas); color:var(--ink); font:15px/1.65 -apple-system,
BlinkMacSystemFont,"Segoe UI",sans-serif; margin:0; }}
body::before {{ background:linear-gradient(90deg,#126b43,#45a66f); content:"";
display:block; height:5px; }}
body > * {{ max-width:1220px; }}
body > a, body > header, body > div, body > section, body > details {{ margin-left:auto;
margin-right:auto; }}
.back-link {{ align-items:center; color:#456052; display:flex; font-weight:650; gap:.45rem;
margin-top:2rem; padding:0 1.5rem; text-decoration:none; width:100%; }}
.back-link:hover {{ color:var(--accent); }}
.page-intro,.meeting-header {{ padding:3rem 1.5rem 2rem; width:100%; }}
.page-intro {{ max-width:920px; }}
.intro-row {{ align-items:flex-end; display:flex; gap:2rem; justify-content:space-between; }}
.eyebrow,.section-label {{ color:var(--accent); font-size:.73rem; font-weight:800;
letter-spacing:.1em; margin:0 0 .45rem; text-transform:uppercase; }}
h1,h2,h3,h4 {{ color:var(--ink); line-height:1.22; }}
h1 {{ font-size:clamp(2rem,5vw,3.35rem); letter-spacing:-.035em; margin:.15rem 0 .8rem;
max-width:980px; }}
h2 {{ letter-spacing:-.018em; }}
.lede {{ color:var(--muted); font-size:1.05rem; margin:0; }}
.count-badge,.local-badge,.summary-badge {{ border-radius:999px; display:inline-flex;
font-size:.72rem; font-weight:750; padding:.35rem .7rem; white-space:nowrap; }}
.count-badge {{ background:#dff3e7; color:#115d3a; }}
.local-badge {{ background:#eef2ef; color:#55645b; }}
.summary-badge {{ background:#e9eaff; color:#4c51a5; }}
.meta-row {{ align-items:center; display:flex; flex-wrap:wrap; gap:.55rem; margin-top:1rem; }}
.meta-pill,.status-pill {{ border:1px solid var(--line); border-radius:999px; color:#536158;
font-size:.78rem; font-weight:700; padding:.27rem .65rem; }}
.status-pill {{ border:0; }}
.status-pending_review {{ background:#fff1cf; color:#76520b; }}
.status-approved {{ background:#dff3e7; color:#115d3a; }}
.status-publishing {{ background:#e9eaff; color:#4c51a5; }}
.status-published {{ background:#dff3e7; color:#115d3a; }}
.status-rejected,.status-blocked {{ background:#fde6e4; color:#8c3030; }}
.card {{ background:var(--surface); border:1px solid var(--line); border-radius:18px;
box-shadow:0 12px 36px rgba(27,48,36,.055); }}
.queue-card,.empty-card,.attention-card,.queue-status,.message-card {{ margin-bottom:1.25rem;
max-width:920px; padding:1.6rem; width:calc(100% - 3rem); }}
.queue-card h2,.empty-card h2 {{ font-size:1.45rem; margin:.2rem 0 .6rem; }}
.queue-card .button {{ margin-top:1.35rem; }}
.empty-card {{ padding:3rem; text-align:center; }}
.empty-icon {{ align-items:center; background:#dff3e7; border-radius:999px; color:#167449;
display:inline-flex; font-size:1.2rem; height:2.6rem; justify-content:center; width:2.6rem; }}
.attention-card {{ border-color:#edc9c5; }}
.attention-card ul {{ margin-bottom:0; }}
.queue-status summary,.metadata-card summary {{ cursor:pointer; font-weight:750; }}
.status-grid {{ display:grid; gap:.7rem; grid-template-columns:repeat(3,1fr); margin-top:1rem; }}
.status-grid div {{ background:#f6f8f7; border-radius:10px; padding:.7rem; }}
.status-grid span {{ color:var(--muted); display:block; font-size:.72rem; }}
.status-grid strong {{ font-size:1.15rem; }}
.review-grid {{ display:grid; gap:1.4rem; grid-template-columns:minmax(0,1fr) 360px;
padding:0 1.5rem 4rem; width:100%; }}
.note-card {{ min-width:0; padding:clamp(1.25rem,3vw,2.3rem); }}
.review-sidebar {{ align-self:start; display:grid; gap:1.2rem; position:sticky; top:1.2rem; }}
.preview-card,.action-card {{ padding:1.15rem; }}
.section-heading {{ align-items:center; border-bottom:1px solid var(--line); display:flex;
justify-content:space-between; margin-bottom:1.3rem; padding-bottom:1rem; }}
.section-heading h2,.action-card h2 {{ font-size:1.25rem; margin:0; }}
.metadata-card {{ background:#f6f8f7; border:1px solid var(--line); border-radius:12px;
margin-bottom:2rem; padding:.8rem 1rem; }}
.metadata-body {{ margin-top:1rem; }}
.metadata-body ul {{ columns:1; font-size:.83rem; }}
.markdown-body {{ color:#2c3831; overflow-wrap:anywhere; }}
.markdown-body > :first-child {{ margin-top:0; }}
.markdown-body > :last-child {{ margin-bottom:0; }}
.markdown-body h2 {{ border-top:1px solid var(--line); font-size:1.55rem; margin:2.6rem 0 1rem;
padding-top:2rem; }}
.markdown-body h2:first-child {{ border-top:0; margin-top:0; padding-top:0; }}
.markdown-body h3 {{ font-size:1.2rem; margin:2rem 0 .75rem; }}
.markdown-body h4 {{ font-size:1rem; margin:1.5rem 0 .55rem; }}
.markdown-body p {{ margin:.6rem 0 1rem; }}
.markdown-body ul,.markdown-body ol {{ margin:.65rem 0 1.25rem; padding-left:1.45rem; }}
.markdown-body li {{ margin:.42rem 0; padding-left:.18rem; }}
.markdown-body li::marker {{ color:#4c8d68; }}
.markdown-body li > ul,.markdown-body li > ol {{ border-left:2px solid #dce9e1; margin:.5rem 0;
padding-left:1.25rem; }}
.markdown-body a {{ color:#126a43; font-weight:600; text-decoration-color:#9ac7ae;
text-underline-offset:3px; }}
.markdown-body a:hover {{ color:#0d5032; text-decoration-color:#0d5032; }}
.markdown-body blockquote {{ border-left:4px solid #8dc4a4; color:#526159; margin:1rem 0;
padding:.15rem 1rem; }}
.markdown-body code {{ background:#edf1ee; border-radius:5px; font-size:.88em;
padding:.12em .32em; }}
.discord-shell {{ background:var(--discord); border-radius:12px; color:#dbdee1; display:flex;
font:14px/1.4 "Segoe UI",sans-serif; gap:.7rem; padding:1rem; }}
.discord-avatar {{ align-items:center; background:#2d8b57; border-radius:50%; color:white;
display:flex; flex:0 0 38px; font-weight:800; height:38px; justify-content:center; }}
.discord-message {{ min-width:0; }}
.discord-author {{ color:#f2f3f5; font-weight:700; }}
.discord-author span {{ background:#5865f2; border-radius:3px; font-size:.58rem; margin-left:.3rem;
padding:.1rem .25rem; vertical-align:2px; }}
.discord-title {{ color:#f2f3f5; font-weight:700; margin-top:.55rem; }}
.discord-date {{ color:#949ba4; font-size:.78rem; margin:.08rem 0 .65rem; }}
.discord-editor-label {{ color:#b5bac1; display:block; font-size:.72rem; font-weight:700;
margin-top:.65rem; }}
.discord-summary {{ background:#383a40; border:1px solid #4e5058; border-radius:6px;
color:#dbdee1; display:block; font:inherit; line-height:1.45; margin-top:.3rem;
min-height:11rem; padding:.65rem; resize:vertical; width:100%; }}
.discord-summary:focus {{ border-color:#80848e; outline:2px solid #5865f2;
outline-offset:1px; }}
.discord-summary-static {{ margin-top:.65rem; white-space:pre-wrap; }}
.discord-editor-help {{ color:#949ba4; font-size:.72rem; margin:.45rem 0 0; }}
.discord-doc-link {{ color:#00a8fc; font-weight:600; margin-top:.7rem; }}
.briefing-editor {{ border:1px solid var(--line); border-radius:9px; display:block;
font:14px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace; margin:1rem 0;
min-height:32rem; padding:1rem; resize:vertical; width:100%; }}
.save-draft {{ background:#e8f2ec; color:var(--accent-dark); margin-top:.6rem; width:100%; }}
.meeting-editor-label {{ color:var(--ink); display:block; font-size:.82rem; font-weight:750;
margin-top:1.5rem; }}
.meeting-note-editor {{ background:#fbfcfb; border:1px solid var(--line); border-radius:9px;
color:var(--ink); display:block; font:14px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace;
margin-top:.5rem; min-height:32rem; padding:1rem; resize:vertical; width:100%; }}
.meeting-note-editor:focus {{ border-color:var(--accent); outline:2px solid #6db88d;
outline-offset:1px; }}
.meeting-editor-help {{ color:var(--muted); font-size:.76rem; margin:.45rem 0 0; }}
.save-note {{ background:#e8f2ec; color:var(--accent-dark); margin-top:.6rem; width:100%; }}
.action-card > p:not(.section-label):not(.privacy-note) {{ color:var(--muted); }}
.actions {{ display:grid; gap:.6rem; margin-top:1.1rem; }}
.actions form {{ margin:0; }}
button,.button {{ border:0; border-radius:9px; cursor:pointer; display:inline-flex;
font:inherit; font-weight:750; justify-content:center; padding:.72rem 1rem;
text-decoration:none; transition:.15s ease; }}
.primary-button,.approve {{ background:var(--accent); color:white; width:100%; }}
.primary-button:hover,.approve:hover {{ background:var(--accent-dark);
transform:translateY(-1px); }}
.reject {{ background:#fff; border:1px solid #e3c0bd; color:var(--danger); width:100%; }}
.reject:hover {{ background:#fff4f3; }}
button:focus-visible,.button:focus-visible,a:focus-visible,summary:focus-visible {{
outline:3px solid #6db88d; outline-offset:3px; }}
.privacy-note {{ border-top:1px solid var(--line); color:var(--muted); font-size:.76rem;
margin:1rem 0 0; padding-top:.9rem; }}
.message-card {{ margin-top:4rem; }}
@media (max-width:880px) {{ .review-grid {{ grid-template-columns:1fr; }}
.review-sidebar {{ position:static; }} .preview-card {{ order:1; }} .action-card {{ order:2; }} }}
@media (max-width:600px) {{ .page-intro,.meeting-header {{ padding:2rem 1rem 1.5rem; }}
.back-link {{ padding:0 1rem; }} .review-grid {{ padding:0 1rem 2rem; }}
.queue-card,.empty-card,.attention-card,.queue-status,.message-card {{ width:calc(100% - 2rem); }}
.intro-row {{ align-items:flex-start; flex-direction:column; gap:1rem; }}
.status-grid {{ grid-template-columns:repeat(2,1fr); }} .note-card {{ padding:1.15rem; }} }}
@media (prefers-reduced-motion:reduce) {{ * {{ scroll-behavior:auto!important;
transition:none!important; }} }}
</style></head><body>{body}</body></html>"""
