name: Remove In Progress Label On Close

on:
  issues:
    types: [closed]

jobs:
  remove-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Remove inprogress label
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const labelName = 'inprogress';
            const labels = context.payload.issue.labels ?? [];
            const hasLabel = labels.some((label) => label.name === labelName);

            if (!hasLabel) {
              console.log(`Issue does not have ${labelName} label`);
              return;
            }

            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: labelName,
            });
